org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.112

mod_id=nua
mod_name=Not Useless Anymore
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=io.github.m1xamm.nua
